In [ ]:
#!pip install numpy
#!pip install matplotlib

In [ ]:
import numpy as np
import pandas as pd   # data processing
from matplotlib import pyplot as plt
import time

In [ ]:
import sys
from google.colab import drive

In [ ]:
drive.mount("/content/gdrive")

sys.path.insert(0,'/content/gdrive/My Drive/GWO/Model')
sys.path.insert(0,'/content/gdrive/My Drive/GWO/Model/Binary_MOGWO')
sys.path

Mounted at /content/gdrive


['/content/gdrive/My Drive/GWO/Model/Binary_MOGWO',
 '/content/gdrive/My Drive/GWO/Model',
 '',
 '/content',
 '/env/python',
 '/usr/lib/python37.zip',
 '/usr/lib/python3.7',
 '/usr/lib/python3.7/lib-dynload',
 '/usr/local/lib/python3.7/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/local/lib/python3.7/dist-packages/IPython/extensions',
 '/root/.ipython']

In [ ]:
from BMOGWO_v1 import *
from ANN_Classifier_v2 import *

In [ ]:
import os
dataset_dir_path = '/content/gdrive/My Drive/GWO/Dataset/UCI_DATA/'
dataset_dirs = os.listdir(dataset_dir_path)
dataset_dirs

['BreastCancer',
 'BreastEW',
 'CongressEW',
 'Exactly',
 'Exactly2',
 'HeartEW',
 'Ionosphere',
 'KrVsKpEW',
 'Lymphography',
 'M-of-n',
 'PenglungEW',
 'Sonar',
 'SpectEW',
 'Tic-tac-toe',
 'Vote',
 'WaveformEW',
 'Wine',
 'Zoo']

In [ ]:
datasets = []

for dir in dataset_dirs:
  datasets.append({ 
      'path': dir +'/' + os.listdir(dataset_dir_path + dir)[0],
      'name': dir
      })

datasets

[{'name': 'BreastCancer', 'path': 'BreastCancer/BreastCancer-final.csv'},
 {'name': 'BreastEW', 'path': 'BreastEW/BreastEW-final.csv'},
 {'name': 'CongressEW', 'path': 'CongressEW/CongressEW-final.csv'},
 {'name': 'Exactly', 'path': 'Exactly/Exactly-final.csv'},
 {'name': 'Exactly2', 'path': 'Exactly2/Exactly2-final.csv'},
 {'name': 'HeartEW', 'path': 'HeartEW/HeartEW-final.csv'},
 {'name': 'Ionosphere', 'path': 'Ionosphere/Ionosphere-final.csv'},
 {'name': 'KrVsKpEW', 'path': 'KrVsKpEW/KrVsKpEW-final.csv'},
 {'name': 'Lymphography', 'path': 'Lymphography/Lymphography-final.csv'},
 {'name': 'M-of-n', 'path': 'M-of-n/M-of-n-final.csv'},
 {'name': 'PenglungEW', 'path': 'PenglungEW/PenglungEW-final.csv'},
 {'name': 'Sonar', 'path': 'Sonar/Sonar-final.csv'},
 {'name': 'SpectEW', 'path': 'SpectEW/SpectEW-final.csv'},
 {'name': 'Tic-tac-toe', 'path': 'Tic-tac-toe/Tic-tac-toe-final.csv'},
 {'name': 'Vote', 'path': 'Vote/Vote-final.csv'},
 {'name': 'WaveformEW', 'path': 'WaveformEW/WaveformEW-

In [ ]:
datasets = datasets[7:]
datasets

[{'name': 'KrVsKpEW', 'path': 'KrVsKpEW/KrVsKpEW-final.csv'},
 {'name': 'Lymphography', 'path': 'Lymphography/Lymphography-final.csv'},
 {'name': 'M-of-n', 'path': 'M-of-n/M-of-n-final.csv'},
 {'name': 'PenglungEW', 'path': 'PenglungEW/PenglungEW-final.csv'},
 {'name': 'Sonar', 'path': 'Sonar/Sonar-final.csv'},
 {'name': 'SpectEW', 'path': 'SpectEW/SpectEW-final.csv'},
 {'name': 'Tic-tac-toe', 'path': 'Tic-tac-toe/Tic-tac-toe-final.csv'},
 {'name': 'Vote', 'path': 'Vote/Vote-final.csv'},
 {'name': 'WaveformEW', 'path': 'WaveformEW/WaveformEW-final.csv'},
 {'name': 'Wine', 'path': 'Wine/Wine-final.csv'},
 {'name': 'Zoo', 'path': 'Zoo/Zoo-final.csv'}]

#### Writing Results

In [ ]:
import pickle

In [ ]:
def writeResults(obj):
  file_path = f'/content/gdrive/My Drive/GWO/Results/{obj["dataset"]}_{obj["iterations"]}.txt'
  resultFile = open(file_path, 'wb')
  pickle.dump(obj, resultFile)
  resultFile.close()

###### Iterations

In [ ]:
iterations = 100

#### Test all datasets

In [ ]:
for dataset in datasets:

  print("\n\nDataset : ", dataset['name'])
  dataframe = pd.read_csv( dataset_dir_path + dataset['path'] )
  bgwo = BMOGWO(dataset = dataframe , greyWolvesNum=8, archiveSize=50, maxIt= iterations)

  start_time = time.time()
  bgwo.optimize()
  end_time = time.time()

  result = {
      'dataset': dataset['name'],
      'dim': bgwo.dim,
      'iterations': bgwo.maxIt,
      'archive': [sol.position for sol in bgwo.archive],
      'archiveCosts': [sol.cost for sol in bgwo.archive],
      'explored': bgwo.explored,
      'runtime': end_time - start_time
  }

  writeResults(result)

Streaming output truncated to the last 5000 lines.
Iteration: 92
alpha: [16.         15.30959606]
beta: [15.         17.76299095]
delta: [18.         16.09743309]
47/47 [==============================] - 0s 2ms/step - loss: 23.0429 - mape: 23.0429
[1. 1. 1. 1. 1. 1. 2.]
[1. 1. 1. 1. 1. 1. 2.]
[1. 1. 1. 1. 1. 1. 2.]
Archive [<GreyWolf.GreyWolf object at 0x7f615b90d490>
[1. 1. 1. 1. 1. 2.]
[1. 1. 1. 1. 2.]

Iteration: 93
alpha: [15.         17.76299095]
beta: [14.         19.72575569]
delta: [17.         15.44971371]
47/47 [==============================] - 0s 2ms/step - loss: 18.9457 - mape: 18.9457
[1. 1. 1. 1. 1. 1. 2.]
[1. 1. 1. 1. 1. 1. 2.]
[1. 1. 1. 1. 1. 1. 2.]
Archive [<GreyWolf.GreyWolf object at 0x7f615b90d490>
[1. 1. 1. 1. 1. 2.]
[1. 1. 1. 1. 2.]

Iteration: 94
alpha: [14.         19.72575569]
beta: [16.         15.30959606]
delta: [15.         17.76299095]
47/47 [==============================] - 0s 2ms/step - loss: 17.8170 - mape: 17.8170
[1. 1. 1. 1. 1. 1. 2.]
[1. 1. 1. 1. 

In [ ]:
result

{'archive': [array([0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0]),
  array([0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0]),
  array([0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0]),
  array([0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0]),
  array([0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0]),
  array([0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0]),
  array([0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0])],
 'dataset': 'Zoo',
 'dim': 16,
 'explored': {0: [array([1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1]),
   array([1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0]),
   array([0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1]),
   array([0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1]),
   array([0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]),
   array([0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1]),
   array([1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1]),
   array([1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1])],
  1: [array([1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,

### Testing Binary GWO

#### Dataset 1

In [ ]:
inFile = "/content/gdrive/My Drive/GWO/Dataset/winequality-red.csv"
data = pd.read_csv(inFile)
data = data.rename(columns={"quality": "target"})
data.head

<bound method NDFrame.head of       fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  target
0               7.4             0.700         0.00  ...       0.56      9.4       5
1               7.8             0.880         0.00  ...       0.68      9.8       5
2               7.8             0.760         0.04  ...       0.65      9.8       5
3              11.2             0.280         0.56  ...       0.58      9.8       6
4               7.4             0.700         0.00  ...       0.56      9.4       5
...             ...               ...          ...  ...        ...      ...     ...
1594            6.2             0.600         0.08  ...       0.58     10.5       5
1595            5.9             0.550         0.10  ...       0.76     11.2       6
1596            6.3             0.510         0.13  ...       0.75     11.0       6
1597            5.9             0.645         0.12  ...       0.71     10.2       5
1598            6.0             0.310         

In [ ]:
def obj_fun(sel_features):
  ann = ANN(sel_features, data)
  ann.train()
  err = ann.test_error()
  no_of_features = np.count_nonzero(sel_features)
  return np.array([no_of_features, err])

In [ ]:
def fun(b):
    #print(sum(b))
    return np.array([ sum(b), 1/sum(b) ])

In [ ]:
bgwo = BMOGWO(dataset = data , greyWolvesNum=8, archiveSize=50, maxIt= iterations)

In [ ]:
bgwo.optimize()

15/15 [==============================] - 0s 1ms/step - loss: 8.6494 - mape: 8.6494
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
Archive [<GreyWolf.GreyWolf object at 0x7fce9b118250>
[1. 1. 1.]
[1. 1.]

Iteration: 0
alpha: [4.         9.37811089]
beta: [2.         9.54323196]
delta: [6.         8.64939308]
15/15 [==============================] - 0s 1ms/step - loss: 9.8616 - mape: 9.8616
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
Archive [<GreyWolf.GreyWolf object at 0x7fce9b0af150>
[1. 1. 1.]
[1. 1.]

Iteration: 1
alpha: [4.         9.37811089]
beta: [6.         8.64939308]
delta: [8.         8.41218376]
15/15 [==============================] - 0s 1ms/step - loss: 8.7694 - mape: 8.7694
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
Archive [<GreyWolf.GreyWolf object at 0x7fce9b118250>
[1. 1. 1.]
[1. 1.]

Iteration: 2
alpha: [6.         8.64939308]
beta: [2.         9.54323196]
delta: [4.         9.37811089]
15/15 [==============================] - 0s 1ms/step - loss: 9.7003 - mape: 9.7003
[1. 1

In [ ]:
print('Dataset1')
for nonD in bgwo.archive:
  print(nonD.cost, nonD.position)

Dataset1
[4.         8.32977104] [0 1 0 1 0 0 0 0 0 1 1]
[5.         8.18117332] [0 1 0 1 0 0 0 0 1 1 1]
[4.         8.38340664] [0 1 0 1 0 0 0 0 0 1 1]
[3.         8.59872341] [0 1 0 1 0 0 0 0 0 0 1]
[2.         9.26126194] [0 0 0 1 0 0 0 0 0 0 1]
[6.         8.02979755] [0 1 0 1 0 0 1 0 1 1 1]
[3.         8.68035412] [0 1 0 1 0 0 0 0 0 0 1]
[5.         8.46032333] [0 1 0 1 0 0 0 0 1 1 1]


In [ ]:
for w in bgwo.greyWolves:
  print(w.cost, w.position, w.dominated)

[5.         8.64452457] [0 1 0 1 0 0 0 0 1 1 1] True
[4.         8.99402905] [0 1 0 1 0 0 0 0 1 0 1] False
[5.         8.60955524] [0 1 0 1 0 0 0 0 1 1 1] True
[5.         9.04942226] [0 1 0 1 0 0 0 0 1 1 1] True
[5.         8.49477291] [0 1 0 1 0 0 0 0 1 1 1] False
[5.        9.2771368] [0 1 0 1 0 0 0 0 1 1 1] True
[5.         8.61601925] [0 1 0 1 0 0 0 0 1 1 1] True
[5.         8.80593872] [0 1 0 1 0 0 0 0 1 1 1] True


In [ ]:
# writing exploration data to file
writeExplorationResults(1, iterations, bgwo.explored)

##### Testing with all features

In [ ]:
from ANN_Classifier_v2 import *

In [ ]:
selected = np.ones(data.shape[1] - 1)
print(selected)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
ann_model = ANN(selected, data)
ann_model.train()

In [ ]:
test_error = ann_model.test_error()
print(test_error)

15/15 [==============================] - 0s 2ms/step - loss: 8.5287 - mape: 8.5287
8.52873706817627


#### DataSet2

In [ ]:
inFile2 = "/content/gdrive/My Drive/GWO/Dataset/UCI_DATA/HeartEW/HeartEW-final.csv"
data2 = pd.read_csv(inFile2)
data2 = data2.rename(columns={"quality": "target"})
data2.head

<bound method NDFrame.head of       0  1  2    3    4  5  6    7  8    9  10  11  12  target
0    34  1  1  118  182  0  2  174  0  0.0   1   0   3       1
1    53  1  4  140  203  1  2  155  1  3.1   3   0   7       2
2    61  1  1  134  234  0  0  145  0  2.6   2   2   3       2
3    68  1  3  118  277  0  0  151  0  1.0   1   1   7       1
4    54  1  4  122  286  0  2  116  1  3.2   2   2   3       2
..   .. .. ..  ...  ... .. ..  ... ..  ...  ..  ..  ..     ...
265  54  1  4  120  188  0  0  113  0  1.4   2   1   7       2
266  68  0  3  120  211  0  2  115  0  1.5   2   0   3       1
267  53  1  4  123  282  0  0   95  1  2.0   2   2   7       2
268  46  1  3  150  231  0  0  147  0  3.6   2   0   3       2
269  35  1  4  120  198  0  0  130  1  1.6   2   0   7       2

[270 rows x 14 columns]>

In [ ]:
def obj_fun2(sel_features):
  ann = ANN(sel_features, data2)
  ann.train()
  err = ann.test_error()
  no_of_features = np.count_nonzero(sel_features)
  return np.array([no_of_features, err])

In [ ]:
bgwo2 = BMOGWO(dataset = data2, greyWolvesNum=8, archiveSize=50, maxIt= iterations)

In [ ]:
bgwo2.optimize()

3/3 [==============================] - 0s 5ms/step - loss: 18.9095 - mape: 18.9095
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
Archive [<GreyWolf.GreyWolf object at 0x7fce98712310>
[1. 1.]

Iteration: 0
alpha: [ 6.         16.04491425]
beta: [ 8.         14.27047443]
delta: [ 6.         16.04491425]
3/3 [==============================] - 0s 4ms/step - loss: 12.0912 - mape: 12.0912
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
Archive [<GreyWolf.GreyWolf object at 0x7fce9882d450>
[1. 1.]

Iteration: 1
alpha: [ 6.         16.04491425]
beta: [ 5.         19.03419685]
delta: [ 5.         19.03419685]
3/3 [==============================] - 0s 4ms/step - loss: 15.8226 - mape: 15.8226
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
Archive [<GreyWolf.GreyWolf object at 0x7fcea0b9c090>
[1. 1.]

Iteration: 2
alpha: [ 6.         12.09121799]
beta: [ 6.         16.04491425]
delta: [ 5.        17.8049469]
3/3 [==============================] - 0s 4ms/step - loss: 16.9332 - mape: 16.9332
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
Archive [<GreyWo

In [ ]:
for nonD in bgwo2.archive:
  print(nonD.cost, nonD.position)

[ 5.         11.11253071] [0 0 0 0 1 0 0 0 1 0 1 1 1]
[ 5.         10.98276138] [0 0 0 0 1 0 0 0 1 0 1 1 1]
[ 5.         10.93576622] [0 0 0 0 1 0 0 0 1 0 1 1 1]
[ 6.         11.45393848] [0 1 0 0 1 0 0 0 1 0 1 1 1]
[ 6.         11.93708134] [0 1 0 0 1 0 0 0 1 0 1 1 1]
[ 6.         13.75484371] [0 1 0 0 1 0 0 0 1 0 1 1 1]
[ 6.         10.87199402] [0 1 0 0 1 0 0 0 1 0 1 1 1]
[ 5.         11.45793915] [0 0 0 0 1 0 0 0 1 0 1 1 1]
[ 6.         13.98187065] [0 1 0 0 1 0 0 0 1 0 1 1 1]
[ 5.         12.17676258] [0 0 0 0 1 0 0 0 1 0 1 1 1]


In [ ]:
# writing exploration data to file
writeExplorationResults(2, iterations, bgwo2.explored)

#### Dataset 3

In [ ]:
inFile3 = "/content/gdrive/My Drive/GWO/Dataset/UCI_DATA/BreastEW/BreastEW-final.csv"
data3 = pd.read_csv(inFile3)
data3 = data3.rename(columns={"quality": "target"})
data3.head

<bound method NDFrame.head of          0      1       2       3  ...       27      28       29  target
0    13.44  21.58   86.18   563.0  ...  0.11120  0.2994  0.07146       1
1    10.49  18.61   66.86   334.3  ...  0.06528  0.2213  0.07842       2
2    10.96  17.62   70.79   365.6  ...  0.09861  0.2289  0.08278       2
3    13.81  23.75   91.56   597.8  ...  0.20130  0.4432  0.10860       1
4    16.46  20.11  109.30   832.9  ...  0.20350  0.3054  0.09519       1
..     ...    ...     ...     ...  ...      ...     ...      ...     ...
563  13.28  20.28   87.32   545.2  ...  0.14920  0.3739  0.10270       1
564  15.28  22.41   98.92   710.6  ...  0.12260  0.3175  0.09772       1
565  24.63  21.60  165.50  1841.0  ...  0.24750  0.3157  0.09671       1
566  14.86  16.94   94.89   673.7  ...  0.07971  0.2525  0.06827       2
567  11.90  14.65   78.11   432.8  ...  0.06042  0.2727  0.10360       2

[568 rows x 31 columns]>

In [ ]:
def obj_fun3(sel_features):
  ann = ANN(sel_features, data3)
  ann.train()
  err = ann.test_error()
  no_of_features = np.count_nonzero(sel_features)
  return np.array([no_of_features, err])

In [ ]:
bgwo3 = BMOGWO(dataset = data3, greyWolvesNum=8, archiveSize=50, maxIt= iterations)

In [ ]:
bgwo3.optimize()

6/6 [==============================] - 0s 3ms/step - loss: 5.9232 - mape: 5.9232
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
Archive [<GreyWolf.GreyWolf object at 0x7fcea2149750>
[1. 1.]

Iteration: 0
alpha: [14.          5.52508402]
beta: [15.         3.8929162]
delta: [14.          5.52508402]
6/6 [==============================] - 0s 3ms/step - loss: 3.7983 - mape: 3.7983
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
Archive [<GreyWolf.GreyWolf object at 0x7fcea2183cd0>
[1. 1. 1. 1.]
[1. 1. 1.]

Iteration: 1
alpha: [14.          5.52508402]
beta: [17.          3.75486398]
delta: [15.          3.79826021]
6/6 [==============================] - 0s 3ms/step - loss: 7.7254 - mape: 7.7254
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
Archive [<GreyWolf.GreyWolf object at 0x7fcea2183cd0>
[1. 1. 1. 1.]
[1. 1. 1.]

Iteration: 2
alpha: [14.          5.52508402]
beta: [15.          3.79826021]
delta: [9.         5.92320013]
6/6 [==============================] - 0s 3ms/step - loss: 4.2642 - ma

In [ ]:
for nonD in bgwo3.archive:
  print(nonD.cost, nonD.position)

[9.         2.41989303] [0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0 0 0 1 0 0 0]
[11.          1.79240048] [0 1 0 1 1 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0 1 0 1 0 0 0]
[12.          1.96368849] [1 1 0 1 1 0 1 0 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0 0 0 1 0 0 0]
[10.          2.53716588] [0 1 0 1 1 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0 0 0 1 0 0 0]
[8.       2.543257] [0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 0 1 0 0 0 1 0 0 0]
[13.          1.73203123] [1 1 1 1 0 0 1 0 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 0 0 0]
[7.         4.33366299] [0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 0 1 0 0 0 1 0 0 0]
[9.         2.29555225] [0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 1 1 0 1 0 0 0 1 0 0 0 1 0 0 0]


In [ ]:
# writing exploration data to file
writeExplorationResults(3, iterations, bgwo3.explored)

#### Dataset 4

In [ ]:
inFile4 = "/content/gdrive/My Drive/GWO/Dataset/UCI_DATA/Ionosphere/Ionosphere-final.csv"
data4 = pd.read_csv(inFile4)
data4 = data4.rename(columns={"quality": "target"})
data4.head

<bound method NDFrame.head of      0  1        2        3  ...       31       32       33  target
0    1  0  0.99539 -0.05889  ... -0.54487  0.18641 -0.45300       1
1    1  0  1.00000 -0.18829  ... -0.06288 -0.13738 -0.02447       2
2    1  0  1.00000 -0.03365  ... -0.24180  0.56045 -0.38238       1
3    1  0  1.00000 -0.45161  ...  1.00000 -0.32382  1.00000       2
4    1  0  1.00000 -0.02401  ... -0.59573 -0.04608 -0.65697       1
..  .. ..      ...      ...  ...      ...      ...      ...     ...
346  1  0  0.83508  0.08298  ... -0.10714  0.90546 -0.04307       1
347  1  0  0.95113  0.00419  ... -0.00035  0.91483  0.04712       1
348  1  0  0.94701 -0.00034  ...  0.00442  0.92697 -0.00577       1
349  1  0  0.90608 -0.01657  ... -0.03757  0.87403 -0.16243       1
350  1  0  0.84710  0.13533  ... -0.06678  0.85764 -0.06151       1

[351 rows x 35 columns]>

In [ ]:
def obj_fun4(sel_features):
  ann = ANN(sel_features, data4)
  ann.train()
  err = ann.test_error()
  no_of_features = np.count_nonzero(sel_features)
  return np.array([no_of_features, err])

In [ ]:
bgwo4 = BMOGWO(dataset = data4, greyWolvesNum=8, archiveSize=50, maxIt= iterations)

In [ ]:
bgwo4.optimize()

4/4 [==============================] - 0s 3ms/step - loss: 8.3555 - mape: 8.3555
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
Archive [<GreyWolf.GreyWolf object at 0x7fce9bd9d810>
[1. 1.]

Iteration: 0
alpha: [14.         10.46875477]
beta: [17.          8.35553455]
delta: [13.         12.04609871]
4/4 [==============================] - 0s 3ms/step - loss: 9.9898 - mape: 9.9898
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
Archive [<GreyWolf.GreyWolf object at 0x7fce9bd9d810>
[1. 1.]

Iteration: 1
alpha: [13.         12.04609871]
beta: [17.          8.35553455]
delta: [14.          9.11959171]
4/4 [==============================] - 0s 3ms/step - loss: 10.8773 - mape: 10.8773
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
Archive [<GreyWolf.GreyWolf object at 0x7fcea1ff85d0>
[1. 1. 1.]
[1. 1.]

Iteration: 2
alpha: [14.          9.11959171]
beta: [16.          9.00365734]
delta: [17.          8.35553455]
4/4 [==============================] - 0s 3ms/step - loss: 8.5520 - mape: 8.5520
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]

In [ ]:
for nonD in bgwo4.archive:
  print(nonD.cost, nonD.position)

[9.         7.29336023] [1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0]
[9.         7.30522871] [1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0]
[9.         7.19908476] [1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0]
[10.         6.6684165] [1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0]
[10.          6.30481339] [1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0]
[11.          6.09182167] [1 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0]
[11.          6.03181553] [1 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0]
[11.         6.4064517] [1 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0]
[12.          4.29007435] [1 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 0 1 0 0 0 1 0 1 0 0]


In [ ]:
# writing exploration data to file
writeExplorationResults(4, iterations, bgwo4.explored)