In [5]:
#!pip install numpy
#!pip install matplotlib

In [6]:
import numpy as np
import pandas as pd   # data processing
from matplotlib import pyplot as plt

In [7]:
import sys
from google.colab import drive

In [8]:
drive.mount("/content/gdrive")

sys.path.insert(0,'/content/gdrive/My Drive/GWO/Model')
sys.path.insert(0,'/content/gdrive/My Drive/GWO/Model/Binary_MOGWO')
sys.path

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


['/content/gdrive/My Drive/GWO/Model/Binary_MOGWO',
 '/content/gdrive/My Drive/GWO/Model',
 '/content/gdrive/My Drive/GWO/Model/Binary_MOGWO',
 '/content/gdrive/My Drive/GWO/Model',
 '',
 '/content',
 '/env/python',
 '/usr/lib/python37.zip',
 '/usr/lib/python3.7',
 '/usr/lib/python3.7/lib-dynload',
 '/usr/local/lib/python3.7/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/local/lib/python3.7/dist-packages/IPython/extensions',
 '/root/.ipython']

In [9]:
inFile = "/content/gdrive/My Drive/GWO/Dataset/winequality-red.csv"
data = pd.read_csv(inFile)
data = data.rename(columns={"quality": "target"})
data.head

<bound method NDFrame.head of       fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  target
0               7.4             0.700         0.00  ...       0.56      9.4       5
1               7.8             0.880         0.00  ...       0.68      9.8       5
2               7.8             0.760         0.04  ...       0.65      9.8       5
3              11.2             0.280         0.56  ...       0.58      9.8       6
4               7.4             0.700         0.00  ...       0.56      9.4       5
...             ...               ...          ...  ...        ...      ...     ...
1594            6.2             0.600         0.08  ...       0.58     10.5       5
1595            5.9             0.550         0.10  ...       0.76     11.2       6
1596            6.3             0.510         0.13  ...       0.75     11.0       6
1597            5.9             0.645         0.12  ...       0.71     10.2       5
1598            6.0             0.310         

In [10]:
from BMOGWO import *
from ANN_Classifier_v2 import *

### Testing Binary GWO

In [ ]:
def obj_fun(sel_features):
  ann = ANN(sel_features, data)
  ann.train()
  err = ann.test_error()
  no_of_features = np.count_nonzero(sel_features)
  return np.array([no_of_features, err])

In [ ]:
def fun(b):
    #print(sum(b))
    return np.array([ sum(b), 1/sum(b) ])

In [ ]:
bgwo = BMOGWO(dim=data.shape[1] - 1, fobj = obj_fun , greyWolvesNum=8, archiveSize=50, maxIt= 100)

In [ ]:
bgwo.optimize()

15/15 [==============================] - 0s 2ms/step - loss: 9.0500 - mape: 9.0500
[1.]
[1.]
[1.]
Archive [<GreyWolf.GreyWolf object at 0x7f14132b8750>]

Iteration: 0
alpha: [ 4.         12.60953704]
beta: [ 4.         12.60953704]
delta: [ 4.         12.60953704]
15/15 [==============================] - 0s 2ms/step - loss: 10.9695 - mape: 10.9695
[1.]
[1.]
[1.]
Archive [<GreyWolf.GreyWolf object at 0x7f140658c190>]

Iteration: 1
alpha: [ 4.         12.56612568]
beta: [ 4.         12.56612568]
delta: [ 4.         12.56612568]
15/15 [==============================] - 0s 2ms/step - loss: 11.0099 - mape: 11.0099
[1.]
[1.]
[1.]
Archive [<GreyWolf.GreyWolf object at 0x7f140a01c750>]

Iteration: 2
alpha: [ 4.         12.34938278]
beta: [ 4.         12.34938278]
delta: [ 4.         12.34938278]
15/15 [==============================] - 0s 2ms/step - loss: 9.3969 - mape: 9.3969
[1.]
[1.]
[1.]
Archive [<GreyWolf.GreyWolf object at 0x7f140acb2dd0>]

Iteration: 3
alpha: [ 4.         12.20578494]
b

In [ ]:
print('Dataset1')
for nonD in bgwo.archive:
  print(nonD.cost, nonD.position)

Dataset1
[ 3.         12.14267343] [0 0 1 0 1 0 1 0 0 0 0]
[ 4.         12.10416054] [0 0 1 0 1 1 1 0 0 0 0]
[ 2.         12.12883719] [0 0 0 0 1 0 1 0 0 0 0]
[ 3.         12.11668558] [0 0 1 0 1 0 1 0 0 0 0]
[ 3.         12.12656665] [0 0 1 0 1 0 1 0 0 0 0]


In [ ]:
bgwo.alpha

0.1

In [ ]:
for w in bgwo.greyWolves:
  print(w.cost, w.position, w.dominated)

[ 3.         12.74358509] [0 0 1 0 1 0 1 0 0 0 0] True
[ 3.         12.33809095] [0 0 1 0 1 0 1 0 0 0 0] False
[ 3.         12.59929307] [0 0 1 0 1 0 1 0 0 0 0] True
[ 3.         12.47929541] [0 0 1 0 1 0 1 0 0 0 0] True
[ 3.         12.59476099] [0 0 1 0 1 0 1 0 0 0 0] True
[ 3.         12.72516193] [0 0 1 0 1 0 1 0 0 0 0] True
[ 3.         12.56551741] [0 0 1 0 1 0 1 0 0 0 0] True
[ 4.         12.96572393] [0 0 1 0 1 0 1 0 0 1 0] True


### Testing with all features

In [ ]:
from ANN_Classifier_v2 import *

In [ ]:
selected = np.ones(data.shape[1] - 1)
print(selected)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
ann_model = ANN(selected, data)
ann_model.train()

In [ ]:
test_error = ann_model.test_error()
print(test_error)

15/15 [==============================] - 0s 1ms/step - loss: 8.2928 - mape: 8.2928
12.744331102532449


#### DataSet2

In [11]:
inFile2 = "/content/gdrive/My Drive/GWO/Dataset/UCI_DATA/HeartEW/HeartEW-final.csv"
data2 = pd.read_csv(inFile2)
data2 = data2.rename(columns={"quality": "target"})
data2.head

<bound method NDFrame.head of       0  1  2    3    4  5  6    7  8    9  10  11  12  target
0    34  1  1  118  182  0  2  174  0  0.0   1   0   3       1
1    53  1  4  140  203  1  2  155  1  3.1   3   0   7       2
2    61  1  1  134  234  0  0  145  0  2.6   2   2   3       2
3    68  1  3  118  277  0  0  151  0  1.0   1   1   7       1
4    54  1  4  122  286  0  2  116  1  3.2   2   2   3       2
..   .. .. ..  ...  ... .. ..  ... ..  ...  ..  ..  ..     ...
265  54  1  4  120  188  0  0  113  0  1.4   2   1   7       2
266  68  0  3  120  211  0  2  115  0  1.5   2   0   3       1
267  53  1  4  123  282  0  0   95  1  2.0   2   2   7       2
268  46  1  3  150  231  0  0  147  0  3.6   2   0   3       2
269  35  1  4  120  198  0  0  130  1  1.6   2   0   7       2

[270 rows x 14 columns]>

In [12]:
def obj_fun2(sel_features):
  ann = ANN(sel_features, data2)
  ann.train()
  err = ann.test_error()
  no_of_features = np.count_nonzero(sel_features)
  return np.array([no_of_features, err])

In [13]:
bgwo2 = BMOGWO(dim=data2.shape[1] - 1, fobj = obj_fun2 , greyWolvesNum=8, archiveSize=50, maxIt= 100)

In [14]:
bgwo2.optimize()

3/3 [==============================] - 0s 4ms/step - loss: 18.5372 - mape: 18.5372
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
Archive [<GreyWolf.GreyWolf object at 0x7f140ad39150>
[1. 1.]

Iteration: 0
alpha: [ 5.         38.54176859]
beta: [ 6.         34.87223226]
delta: [ 7.        30.6637662]
3/3 [==============================] - 0s 3ms/step - loss: 20.7115 - mape: 20.7115
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
Archive [<GreyWolf.GreyWolf object at 0x7f140ad39510>
[1. 1.]

Iteration: 1
alpha: [ 6.         34.87223226]
beta: [ 7.        30.6637662]
delta: [ 7.        30.6637662]
3/3 [==============================] - 0s 4ms/step - loss: 22.6003 - mape: 22.6003
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
Archive [<GreyWolf.GreyWolf object at 0x7f1413574850>
[1. 1.]

Iteration: 2
alpha: [ 5.         38.54176859]
beta: [ 7.        30.6637662]
delta: [ 5.         38.54176859]
3/3 [==============================] - 0s 4ms/step - loss: 21.1845 - mape: 21.1845
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
Archive [<GreyWolf.Gre

In [15]:
for nonD in bgwo2.archive:
  print(nonD.cost)

[ 1.         21.77390076]
[ 1.         21.81348095]
[ 2.         21.68855613]
[ 2.         21.67296321]
[ 1.         21.95695575]


#### Dataset 3

In [16]:
inFile3 = "/content/gdrive/My Drive/GWO/Dataset/UCI_DATA/BreastEW/BreastEW-final.csv"
data3 = pd.read_csv(inFile3)
data3 = data3.rename(columns={"quality": "target"})
data3.head

<bound method NDFrame.head of          0      1       2       3  ...       27      28       29  target
0    13.44  21.58   86.18   563.0  ...  0.11120  0.2994  0.07146       1
1    10.49  18.61   66.86   334.3  ...  0.06528  0.2213  0.07842       2
2    10.96  17.62   70.79   365.6  ...  0.09861  0.2289  0.08278       2
3    13.81  23.75   91.56   597.8  ...  0.20130  0.4432  0.10860       1
4    16.46  20.11  109.30   832.9  ...  0.20350  0.3054  0.09519       1
..     ...    ...     ...     ...  ...      ...     ...      ...     ...
563  13.28  20.28   87.32   545.2  ...  0.14920  0.3739  0.10270       1
564  15.28  22.41   98.92   710.6  ...  0.12260  0.3175  0.09772       1
565  24.63  21.60  165.50  1841.0  ...  0.24750  0.3157  0.09671       1
566  14.86  16.94   94.89   673.7  ...  0.07971  0.2525  0.06827       2
567  11.90  14.65   78.11   432.8  ...  0.06042  0.2727  0.10360       2

[568 rows x 31 columns]>

In [17]:
def obj_fun3(sel_features):
  ann = ANN(sel_features, data3)
  ann.train()
  err = ann.test_error()
  no_of_features = np.count_nonzero(sel_features)
  return np.array([no_of_features, err])

In [18]:
bgwo3 = BMOGWO(dim=data3.shape[1] - 1, fobj = obj_fun3 , greyWolvesNum=8, archiveSize=50, maxIt= 100)

In [19]:
bgwo3.optimize()

6/6 [==============================] - 0s 2ms/step - loss: 2.3775 - mape: 2.3775
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
Archive [<GreyWolf.GreyWolf object at 0x7f14132aeed0>
[1. 1. 1.]
[1. 1.]

Iteration: 0
alpha: [18.         35.33828351]
beta: [19.         35.15886937]
delta: [14.         35.55993667]
6/6 [==============================] - 0s 2ms/step - loss: 7.3943 - mape: 7.3943
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
Archive [<GreyWolf.GreyWolf object at 0x7f1413439910>
[1. 1. 1. 1.]
[1. 1. 1.]

Iteration: 1
alpha: [18.         35.33828351]
beta: [19.         35.15886937]
delta: [ 9.         35.93624036]
6/6 [==============================] - 0s 4ms/step - loss: 3.7576 - mape: 3.7576
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
Archive [<GreyWolf.GreyWolf object at 0x7f1413439910>
[1. 1. 1. 1.]
[1. 1. 1.]

Iteration: 2
alpha: [15.         35.44368764]
beta: [14.         35.55993667]
delta: [ 9.         35.93624036]
6/6 [==============================] - 0s 2ms/

In [20]:
for nonD in bgwo3.archive:
  print(nonD.cost)

[13.      31.57278]
[11.         34.63556435]
[ 8.         34.95586674]
[11.         34.68389608]
[ 8.         35.11659599]
[ 9.         35.22569052]
[10.         34.78529349]
[ 8.         34.61455707]
[12.         34.45078861]
[ 9.         34.79203213]
[ 9.         34.91659311]


#### Dataset 4

In [21]:
inFile4 = "/content/gdrive/My Drive/GWO/Dataset/UCI_DATA/Ionosphere/Ionosphere-final.csv"
data4 = pd.read_csv(inFile4)
data4 = data4.rename(columns={"quality": "target"})
data4.head

<bound method NDFrame.head of      0  1        2        3  ...       31       32       33  target
0    1  0  0.99539 -0.05889  ... -0.54487  0.18641 -0.45300       1
1    1  0  1.00000 -0.18829  ... -0.06288 -0.13738 -0.02447       2
2    1  0  1.00000 -0.03365  ... -0.24180  0.56045 -0.38238       1
3    1  0  1.00000 -0.45161  ...  1.00000 -0.32382  1.00000       2
4    1  0  1.00000 -0.02401  ... -0.59573 -0.04608 -0.65697       1
..  .. ..      ...      ...  ...      ...      ...      ...     ...
346  1  0  0.83508  0.08298  ... -0.10714  0.90546 -0.04307       1
347  1  0  0.95113  0.00419  ... -0.00035  0.91483  0.04712       1
348  1  0  0.94701 -0.00034  ...  0.00442  0.92697 -0.00577       1
349  1  0  0.90608 -0.01657  ... -0.03757  0.87403 -0.16243       1
350  1  0  0.84710  0.13533  ... -0.06678  0.85764 -0.06151       1

[351 rows x 35 columns]>

In [22]:
def obj_fun4(sel_features):
  ann = ANN(sel_features, data4)
  ann.train()
  err = ann.test_error()
  no_of_features = np.count_nonzero(sel_features)
  return np.array([no_of_features, err])

In [23]:
bgwo4 = BMOGWO(dim=data4.shape[1] - 1, fobj = obj_fun4 , greyWolvesNum=8, archiveSize=50, maxIt= 100)

In [ ]:
bgwo4.optimize()

4/4 [==============================] - 0s 3ms/step - loss: 12.7467 - mape: 12.7467
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
Archive [<GreyWolf.GreyWolf object at 0x7f140ad44b10>
[1. 1. 1.]
[1. 1.]

Iteration: 0
alpha: [17.         33.61912501]
beta: [10.        38.2598131]
delta: [14.         37.28925378]
4/4 [==============================] - 0s 4ms/step - loss: 9.8419 - mape: 9.8419
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
Archive [<GreyWolf.GreyWolf object at 0x7f140ad44b10>
[1. 1. 1.]
[1. 1.]

Iteration: 1
alpha: [14.         35.47064551]
beta: [10.        38.2598131]
delta: [16.         31.19699622]
4/4 [==============================] - 0s 3ms/step - loss: 9.5579 - mape: 9.5579
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
Archive [<GreyWolf.GreyWolf object at 0x7f1412ddc090>
[1. 1. 1.]
[1. 1.]

Iteration: 2
alpha: [14.         33.84227208]
beta: [10.        38.2598131]
delta: [16.         31.19699622]
4/4 [==============================] - 0s 3ms/step - loss: 9.0893 - mape: 9.0893

In [ ]:
for nonD in bgwo4.archive:
  print(nonD.cost)

[11.         28.06975249]
[ 9.         32.49104492]
[13.         28.03193711]
[ 9.        31.4343509]
[10.         28.43237278]
[10.         29.48487943]
[12.         29.09421724]
[12.         19.09887465]
