## GreyWolf Optimizer

In [1]:
!pip install numpy

In [7]:
import numpy as np

In [8]:
class wolf:
    
    def __init__(self, dim):
        self.position = 100 * np.random.rand(dim)
        self.obj_score = float('inf')

In [15]:
def GWO(obj_fun, soln_dim, wolves_n, iter_n):
    
    # obj_fun   - objective function to be minimized
    # soln_dim  - dimension of solution vector
    # wolves_n    - no. of searching wolves
    # iter_n    - no of iterations
    
    wolves = []
    
    # 1] Initialize positions of wolves randomly
    
    for i in range(wolves_n):
        w = wolf(soln_dim)
        print(w.position)
        wolves.append(w)
    
    alpha , beta, delta = wolves[:3]
    
    alpha_score = []
    
    # 2] Loop 3-4  iter_n times
    
    for i in range(iter_n):
        
    #   3] Calculate objective function for all wolves and find best 3 alpha, beta & gamma
        
        for w in wolves:
            w.obj_score = obj_fun(w.position)
            
            if w.obj_score <= alpha.obj_score:
                delta = beta
                beta = alpha
                alpha = w
            
            elif w.obj_score <= beta.obj_score:
                delta = beta
                beta = w
                
            elif w.obj_score <= delta.obj_score:
                delta = w
                
        alpha_score.append(alpha.obj_score)
        
        
    #   4] Update positions of rest of wolves based on GWO mathematical formula
    
        for w in wolf:
            
    
    # 5] Return best solution (alpha)
    
    
    return 0
    

IndentationError: expected an indented block (<ipython-input-15-629d33f59adf>, line 53)

In [13]:
def dummy_obj_fun(sol):
    return sum(sol)

In [14]:
GWO(dummy_obj_fun, 2, 10, 10)

[49.4945267   4.47654826]
[67.58513868 50.63875191]
[86.19325909  1.32807372]
[ 1.23978492 70.53582364]
[47.3842141  26.37349744]
[40.25136465 12.85566678]
[71.64234312 95.86598803]
[97.461234   58.34075616]
[81.11040739 83.00897104]
[94.45821653 61.12945766]


0

In [17]:
SearchAgents_no=50
dim = 3
ub =[100] * dim 
lb = [-100] * dim

In [18]:
Positions = np.zeros((SearchAgents_no, dim))
print(Positions)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
for i in range(dim):
    Positions[:, i] = (np.random.uniform(0, 1, SearchAgents_no) * (ub[i] - lb[i]) + lb[i])
    print("Positions")
    print(Positions)

Positions
[[  6.6017555    0.           0.        ]
 [ 49.38299734   0.           0.        ]
 [ 90.27821096   0.           0.        ]
 [-21.87989835   0.           0.        ]
 [ 66.35113587   0.           0.        ]
 [-78.50307712   0.           0.        ]
 [ 60.86061343   0.           0.        ]
 [  2.41176903   0.           0.        ]
 [-80.60993634   0.           0.        ]
 [ 65.76181902   0.           0.        ]
 [ 26.3658188    0.           0.        ]
 [ 95.3545442    0.           0.        ]
 [ 30.48443103   0.           0.        ]
 [-80.06061526   0.           0.        ]
 [-85.61325528   0.           0.        ]
 [-27.45030642   0.           0.        ]
 [ 83.82955979   0.           0.        ]
 [ 37.20608084   0.           0.        ]
 [ 47.72352306   0.           0.        ]
 [ 88.25759561   0.           0.        ]
 [ 84.03612899   0.           0.        ]
 [-56.5285954    0.           0.        ]
 [ 24.145016     0.           0.        ]
 [-19.99844219   0.     