## GreyWolf Optimizer

In [1]:
!pip install numpy

In [7]:
import numpy as np

In [8]:
class wolf:
    
    def __init__(self, dim):
        self.position = 100 * np.random.rand(dim)
        self.obj_score = float('inf')

In [15]:
def GWO(obj_fun, soln_dim, wolves_n, iter_n):
    
    # obj_fun   - objective function to be minimized
    # soln_dim  - dimension of solution vector
    # wolves_n    - no. of searching wolves
    # iter_n    - no of iterations
    
    wolves = []
    
    # 1] Initialize positions of wolves randomly
    
    for i in range(wolves_n):
        w = wolf(soln_dim)
        print(w.position)
        wolves.append(w)
    
    alpha , beta, delta = wolves[:3]
    
    alpha_score = []
    
    # 2] Loop 3-4  iter_n times
    
    for i in range(iter_n):
        
    #   3] Calculate objective function for all wolves and find best 3 alpha, beta & gamma
        
        for w in wolves:
            w.obj_score = obj_fun(w.position)
            
            if w.obj_score <= alpha.obj_score:
                delta = beta
                beta = alpha
                alpha = w
            
            elif w.obj_score <= beta.obj_score:
                delta = beta
                beta = w
                
            elif w.obj_score <= delta.obj_score:
                delta = w
                
        alpha_score.append(alpha.obj_score)
        
        
    #   4] Update positions of rest of wolves based on GWO mathematical formula
    
        for w in wolf:
            
    
    # 5] Return best solution (alpha)
    
    
    return 0
    

IndentationError: expected an indented block (<ipython-input-15-629d33f59adf>, line 53)

In [13]:
def dummy_obj_fun(sol):
    return sum(sol)

In [14]:
GWO(dummy_obj_fun, 2, 10, 10)

[49.4945267   4.47654826]
[67.58513868 50.63875191]
[86.19325909  1.32807372]
[ 1.23978492 70.53582364]
[47.3842141  26.37349744]
[40.25136465 12.85566678]
[71.64234312 95.86598803]
[97.461234   58.34075616]
[81.11040739 83.00897104]
[94.45821653 61.12945766]


0

In [21]:
SearchAgents_no=50
dim = 3
ub =[100] * dim 
lb = [-100] * dim

In [26]:
Positions = np.zeros((SearchAgents_no, dim))
print(Positions)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [27]:
for i in range(dim):
    Positions[:, i] = (np.random.uniform(0, 1, SearchAgents_no) * (ub[i] - lb[i]) + lb[i])
    print("Positions")
    print(Positions)

Positions
[[-56.18927652   0.           0.        ]
 [ 96.29036151   0.           0.        ]
 [-52.24688901   0.           0.        ]
 [ 42.47596401   0.           0.        ]
 [  3.42395051   0.           0.        ]
 [ 19.93615667   0.           0.        ]
 [ 72.5569554    0.           0.        ]
 [-96.21918149   0.           0.        ]
 [-32.76744437   0.           0.        ]
 [-46.45422611   0.           0.        ]
 [  7.97618817   0.           0.        ]
 [ 31.72482849   0.           0.        ]
 [ -3.09083406   0.           0.        ]
 [ 65.73082263   0.           0.        ]
 [-81.3543667    0.           0.        ]
 [-59.33664324   0.           0.        ]
 [-23.92991851   0.           0.        ]
 [ 62.23584004   0.           0.        ]
 [ 51.11387359   0.           0.        ]
 [-10.24810717   0.           0.        ]
 [ 90.63705253   0.           0.        ]
 [-45.88659779   0.           0.        ]
 [-15.30595589   0.           0.        ]
 [-61.68913048   0.     

In [24]:
Positions

array([[ 67.6927997 ,  53.66185112, -18.67431927],
       [ -6.40594787,  53.74748642,  85.35587415],
       [-15.86038406, -33.91018286,  12.34720935],
       [ 35.40369847, -87.51386191, -49.27372224],
       [ 33.38098876,  79.47060858,  19.23266108],
       [ 51.09224629, -63.47062513,  48.24459389],
       [ 95.50222333, -44.73211358,  10.16878661],
       [ -8.15181524, -25.49548512,  36.61482372],
       [ 46.64814842, -29.71037215, -28.21459468],
       [-96.46733971,  33.00182909, -88.40838644],
       [-16.6057877 , -66.01520751,  74.00180478],
       [ 97.9697665 ,   8.93636258,  62.35138303],
       [ 41.97907582, -29.39926955, -60.28669035],
       [ 17.30807295,  -0.34257631,  25.29408919],
       [-61.19699108,   2.20593185,  22.69452642],
       [-42.16305269, -43.27919087, -62.8560007 ],
       [ 94.5159563 , -40.21819376,  98.27043672],
       [  8.65055757,  63.24573781,  69.98796527],
       [ 68.26660883, -25.20624306,  51.95334001],
       [-74.39901222, -42.51714